### ISSUE TITLE
No 'Install folder' inside the 'build folder'

### ISSUE THREAD

**Issue by qiaow371** [sccn/liblsl#123]
When I finished configuring the liblsl project. There is no **'install folder'** inside the **'build folder'.**

I will appreciate it if anyone could help me with this issue.

**Comment by tstenner** [comment]
At popular request the location for the install folder isn't set, so CMake chooses one (somewhere).

You can either:

- enable `LSL_COMFY_DEFAULTS` by passing `-DLSL_COMFY_DEFAULTS=ON` the first time you run CMake or add the variable to your Visual Studio CMake variables
- set `CMAKE_INSTALL_PREFIX` to the path you want the built files to be copied to or
- look through the build log for the location CMake chose, e.g. `-- Installing: /some/path/somewhere/build/install/lib/liblsl.so.1.14.0`
