### ISSUE TITLE
compiling problem under ARM core (Nvidia Jetson Nano)?

### ISSUE THREAD

**Issue by Thanh-Binh** [sccn/liblsl#124]
I am trying to compile this SW in Nano, but by runing 
cmake ..

I have error:
CMake Error at LSL/liblsl/CmakeLists.txt:162 (target_link_libraries: Object library target "lslboost" may not link to anything

Do you have any idea for solving this problem? Thanks

**Comment by tstenner** [comment]
For embedded devices it's easier to run the [standalone_compilation_linux.sh](https://github.com/sccn/liblsl/blob/master/standalone_compilation_linux.sh) script.

Of course, CMake is also supposed to work on embedded devices. Could you check the CMake version (`cmake --version`)?

**Comment by Thanh-Binh** [comment]
Thanks
Can I compile it as static library?

**Comment by tstenner** [comment]
Sure, just replace "-shared" with "-static" in the script.
