### ISSUE TITLE
liblsl install on Fedora

### ISSUE THREAD

**Issue by lvanname** [sccn/liblsl#133]
I was wondering if there was a way to install liblsl on Fedora? Given that the packages are Debian, I am having trouble installing on Fedora. 

I am currently trying to run a Ue4 project with the LSL plugin and I get the following error: 
`/home/ue4/project/test: error while loading shared libraries: liblsl64.s0.1.13.0: cannot open shared object file: No such file or directory`

I was thinking that I needed to install the current release of liblsl after reading [this](https://github.com/labstreaminglayer/App-LabRecorder/issues/23) issue, but with Fedora as my OS, I couldn't find a way to install the current release.

**Comment by tstenner** [comment]
I don't have a local Fedora installation, but building liblsl on Fedora should be straightforward. With a C++ compiler and CMake installed, you can just run

```
git clone --depth=1 https://github.com/sccn/liblsl.git
cmake -S liblsl -B liblsl/build -DCMAKE_COMFY_DEFAULTS=ON
cmake --build liblsl/build --target install
```

and you'll get everything in the `liblsl/build/install` folder. This way, it might even be possible (untested, but while you're at it… :wink:) to run `cd liblsl/build; cpack -G RPM` to build RPM packages.
