### ISSUE TITLE
CMake install broken for static builds

### ISSUE THREAD

**Issue by chausner** [sccn/liblsl#138]
When setting `LSL_BUILD_STATIC=ON`, the CMake install command fails with:
```
CMake Error: install(EXPORT "LSLTargets" ...) includes target "lsl" which requires target "lslobj" that is not in any export set.
CMake Error: install(EXPORT "LSLTargets" ...) includes target "lsl" which requires target "lslboost" that is not in any export set.
CMake Error in CMakeLists.txt:
  export called with target "lsl" which requires target "lslobj" that is not
  in any export set.


CMake Error in CMakeLists.txt:
  export called with target "lsl" which requires target "lslboost" that is
  not in any export set.
```

Seems commit 730e13050142f7140a8b3de85b2a2b164eb1bc0e broke it.

**Comment by cboulay** [comment]
I don't have time to look into this at the moment. Maybe @tstenner will tomorrow. Either way, we need a little more info.

What platform?
What version of cmake?

**Comment by chausner** [comment]
- Windows x64, MSVC 19.29.30133.0
- CMake 3.21.1
- CMake options
  - BUILD_SHARED_LIBS=OFF
  - LSL_BUILD_STATIC=ON
  - LSL_BUNDLED_PUGIXML=OFF
  - lslgitrevision=v1.15.2
  - lslgitbranch=master

**Comment by tstenner** [comment]
I have identified the problem but it might take a few days to verify that my solution doesn't break anything else. I'll push a PR this or the next evening.
