### ISSUE TITLE
Unable to use it ...

### ISSUE THREAD

**Issue by toncho11** [sccn/liblsl#162]
This s*** on so many levels ... Incredible!

I can not use your release lsl.dll in Visual Studio 2019 and compiled with .NET 4.6.2. It does not accept the assembly. 
When you try to recompile it does not work either. You have selected .NET Standard 2.0 ... for what reason? 
You can not select .NET 4.6.2 in Visual Studio soemetimes. It has been removed and it can not be added. Adding targeting framework does not work. Other people have the same problem ... 
Nothing works ...
So many hours lost for nothing ...

**Comment by cboulay** [comment]
If you have issues related to .NET then you can start by asking at the Csharp repo:
https://github.com/labstreaminglayer/liblsl-Csharp/

Also, @dmedine has been working on a modern dotnet interpretation which you might be more interested in:
https://github.com/Diademics-Pty-Ltd/LSL-dotnet

Happy New Year!

**Comment by toncho11** [comment]
Thanks!
I made a mistake, my post was for the https://github.com/labstreaminglayer/liblsl-Csharp/ respository.
Maybe this new one is better.
Thanks! Happy new year you too!
