### ISSUE TITLE
LSL for Android (C++ project)

### ISSUE THREAD

**Issue by VladimirR46** [sccn/liblsl#191]
Hello!

Our team wants to use an Samsung galaxy Tab S7 for a series of experiments. Our stimulus program is written in Qt Creator (c++ qt 6.5). The program compiles successfully and runs on an galaxy Tab with Android. The program is built for the processor architecture arm64-v8a. We want to add lsl to the program to send event markers. How can we do that?

Unfortunately, we do not have a development specialist for the Android platform. At this point I understand that we have the option to compile the library using Android Studio and get aar (.so) file for Java. And then, using (https://doc.qt.io/qt-6/android-3rdparty-libs.html) method use Java library in  in our C++ code. (https://doc.qt.io/qt-6/qtcore-platform-androidnotifier-example.html) But I don't like this approach very much since it breaks Qt's single code base. (We also build this program for Windows and MacOS, no problem with these platforms!)

Can we somehow build a library (get a ".so" file) to use in a C++ project and connect it in cmake as:
```
find_package(LSL 1.13.0 REQUIRED
      HINTS ${LSL_INSTALL_ROOT}
      "${CMAKE_CURRENT_LIST_DIR}/../../LSL/liblsl/build/"
      "${CMAKE_CURRENT_LIST_DIR}/../../LSL/liblsl/build/install"
      PATH_SUFFIXES share/LSL
)
```

Thank you so much for any help!

**Comment by VladimirR46** [comment]
Thanks for the quick response!

I created a simple test project for Windows using MinGW_64. In CMake I added:

```
include(FetchContent)

FetchContent_Declare(LSL
            GIT_REPOSITORY https://github.com/sccn/liblsl.git
            FIND_PACKAGE_ARGS
    )
set(LSL_BUILD_STATIC ON)
FetchContent_MakeAvailable(LSL)

target_link_libraries(TestApp PRIVATE Qt${QT_VERSION_MAJOR}::Widgets LSL)
```
But there is an error at the linking stage.

![image](https://user-images.githubusercontent.com/38318731/231909667-0daaf487-7d77-445c-ae5d-4d30be23eabd.png)

**Comment by cboulay** [comment]
Try `lsl` (lower case), or `LSL::lsl`.

**Comment by VladimirR46** [comment]
Thank you so much!

If I use MSVC2019 64bit and 
`target_link_libraries(TestApp PRIVATE Qt${QT_VERSION_MAJOR}::Widgets lsl)`
The project compiles successfully! If I use MinGW_64 I get some errors. But I think it doesn't matter because I managed to build it for Windows using MSVC.

But if I try to use "Android Qt 6.5.0 Clang arm64-v8a" I get the following errors:


![image](https://user-images.githubusercontent.com/38318731/231916530-3599debb-cb31-43a3-b9c4-8aa5173523d2.png)

**Comment by cboulay** [comment]
Try adding `set(LSL_OPTIMIZATIONS OFF)` after the line to set static library.

**Comment by cboulay** [comment]
Also, paging @tstenner .

**Comment by tstenner** [comment]
The multicast enumeration code only works for api level 24 and later. There was a workaround for niche platforms (neither windows, macOS nor android < 24) that had a wrong function name and in three years nobody noticed it...

I don't know if you can see those here, but when you fork the repository there's a [predefined Gitlab CI job to build Android libraries](https://github.com/sccn/liblsl/blob/master/.github/workflows/android.yml) you can start for any branch and have it built on a build machine with everything preinstalled

**Comment by VladimirR46** [comment]
Thank you all so much for your help!

The problem was that I installed the repository by mistake `https://github.com/tstenner/liblsl.git`

Now I use this code and it works!!!

```
include(FetchContent)

FetchContent_Declare(LSL
            GIT_REPOSITORY https://github.com/sccn/liblsl.git
            FIND_PACKAGE_ARGS
    )
set(LSL_BUILD_STATIC ON)
set(LSL_OPTIMIZATIONS OFF)
FetchContent_MakeAvailable(LSL)
```

Thank you!
