### ISSUE TITLE
Standalone Script asks for lslboost/serialization_objects.cpp

### ISSUE THREAD

**Issue by jmuellers** [sccn/liblsl#205]
Hi, in commit https://github.com/sccn/liblsl/commit/cea921024562de8d1d61905d1b9825c4fe640f93 you deleted lslboost/serialization_objects.cpp, which required in [standalone_compilation_linux.sh](https://github.com/sccn/liblsl/blob/master/standalone_compilation_linux.sh). We are trying to compile your library for Raspberry Pi. It would be greatly appreciated if you could test compilation and fix.

Cheers

**Comment by tstenner** [comment]
Good find, the script isn't covered by the CI jobs. The file isn't needed with the latest master, so I just removed it.
