### ISSUE TITLE
Unable to Build or Use on macOS Silicon (arm64)

### ISSUE THREAD

**Issue by Maximeadanteriora** [sccn/liblsl#226]
I am experiencing multiple issues when trying to set up `liblsl` on macOS with Apple Silicon (`arm64`). Despite following the documented methods and troubleshooting steps, I am unable to successfully build or use the library. I have tried several approaches:

1. Installing via Homebrew:
`brew install labstreaminglayer/tap/lsl`

The build fails with architecture mismatch errors and missing header files.

2. Building `liblsl` manually:
`git clone https://github.com/sccn/liblsl.git mkdir build && cd build cmake .. -DCMAKE_OSX_ARCHITECTURES=arm64 cmake --build . --target install`

The build fails with `stdlib.h` missing and other `mach-o` architecture issues.

3. Attempting to use prebuilt binaries:
No ARM64-compatible binaries are available on the GitHub releases page.

4. Installing `pylsl` via `pip`:
`pip install pylsl`

While `pylsl` installs, it throws runtime errors because `liblsl64.dylib` is incompatible (`x86_64` architecture, not `arm64`).

**System Details**:
- **OS**: macOS 15.1.1 Sequoia (Apple Silicon, `arm64`)
- **Python Version**: 3.9 (Conda environment)
- **CMake Version**: 3.27
- **Homebrew Version**: 4.x
- **liblsl Version**: Latest (from GitHub and Homebrew)

**Error Logs**:
1. Homebrew Build Error:
`[ERROR] mach-o architecture mismatch (need 'arm64', found 'x86_64')`

2. Manual Build Error:
`fatal error: 'stdlib.h' file not found`

3. Runtime Error with `pylsl`:
`RuntimeError: liblsl library 'liblsl64.dylib' found but could not be loaded - possible platform/architecture mismatch.`

**Expected Behavior**: 
Provide a prebuilt `liblsl64.dylib` binary compatible with Apple Silicon (`arm64`) and ensure compatibility with `pylsl` on macOS ARM64.

**Additional Context**:
I have attempted to manually build `liblsl` and install `pylsl` in various ways, including through Homebrew, Conda, and direct source compilation. All approaches fail due to architecture compatibility issues or missing binaries for ARM64. Please provide guidance on how to set up `liblsl` or ensure compatibility for macOS Apple Silicon.

**Comment by cboulay** [comment]
I use liblsl on Apple Silicon all the time. In fact, I'm using it on my M4 Pro right now (MacOS 15.1.1) and I previously used it on my M1Pro.
I typically use the `brew install labstreaminglayer/tap/lsl` command to install it.

Any chance you installed the wrong Xcode SDK or that you might have overwritten the default toolchain with the wrong toolchain?

**Comment by Maximeadanteriora** [comment]
@cboulay no, it was already installed, just couldn't run - Fixed it using `liblsl64.dylib` from [here](https://github.com/WesselVS/liblsl/releases/tag/fix_release)

The root cause was the lack of a compatible `liblsl64.dylib` file for macOS Apple Silicon (arm64).

Once the correct file was obtained, setting the DYLD_LIBRARY_PATH resolved any library loading issues. Only thing left was the macOS Gatekeeper flagging the new file as unverified, preventing it from being used initially. Removing the quarantine attribute in the terminal resolved this minor issue.

Once the correct file (`arm64`) was added and made accessible via the environment variable, everything worked as expected!
