### ISSUE TITLE
floating point conversion is locale dependent

### ISSUE THREAD

**Issue by sheinke** [sccn/liblsl#24]
Hi there,
I have encountered a rather persistent issue with the liblsl-library on Ubuntu 16.04 LTS, compiling with GCC 5.4.0:
While other hosts in the network (including the localhost) can **detect** outgoing streams, there seems to be a problem with the input parsing: Every field of the stream_info object that is returned by the lsl::resolve_streams function is empty (except for IPv4 and IPv6 addresses). My Ubuntu machine can receive data perfectly fine, this issue seems to concern outgoing connections only. This behavior is not influenced by the receiving machine, I get the same error on Ubuntu and Windows 10. When trying to build a stream_inlet with this faulty stream_info, it says:

*Note: The stream named '(invalid: bad lexical cast: source type value could not be interpreted as target)' could not be recovered automatically if its provider crashed because it does not specify a unique data source ID.*

The part mentioning the failed cast seems to originate in the boost-backend.

This is an excerpt from the sender code:
```cpp
// the issue persists when I change data format or frequency
lsl::stream_info info("SimpleStream", "EEG", 90, 1000.0f, lsl::channel_format_t::cf_double64, "DUMMY_ID");
lsl::stream_outlet outlet(info);
outlet.wait_for_consumers(600);
```

When I print the XML-info for the outlet on the sending machine, everything seems to be correct:
```xml
<?xml version="1.0"?>
<info>
    <name>SimpleStream</name>
    <type>EEG</type>
    <channel_count>90</channel_count>
    <nominal_srate>1000</nominal_srate>
    <channel_format>double64</channel_format>
    <source_id>DUMMY_ID</source_id>
    <version>1,1000000000000001</version>
    <created_at>340,01528632399999</created_at>
    <uid>c7a69651-42af-4749-ae12-706dbae31731</uid>
    <session_id>default</session_id>
    <hostname>schrottpad</hostname>
    <v4address></v4address>
    <v4data_port>16572</v4data_port>
    <v4service_port>16572</v4service_port>
    <v6address></v6address>
    <v6data_port>16573</v6data_port>
    <v6service_port>16573</v6service_port>
    <desc />
</info>
```

The XML for the detected stream_info on the receiving machine is completely useless:
```xml
<?xml version="1.0"?>
<info>
    <name></name>
    <type></type>
    <channel_count>0</channel_count>
    <nominal_srate>0</nominal_srate>
    <channel_format>undefined</channel_format>
    <source_id></source_id>
    <version>0</version>
    <created_at>0</created_at>
    <uid></uid>
    <session_id></session_id>
    <hostname></hostname>
    <v4address>192.168.178.120</v4address>
    <v4data_port>0</v4data_port>
    <v4service_port>0</v4service_port>
    <v6address>2003:d1:ef0c:5700:d42c:6e43:2908:3998</v6address>
    <v6data_port>0</v6data_port>
    <v6service_port>0</v6service_port>
    <desc />
</info>
```

I have already played around with the lsl_api.conf file, but I was not able to resolve the issue. I remember that during the compilation of liblsl, GCC put out a warning about several outdated headers, including one dealing with endianess. 

I am running out of ideas, so I hope you can help me.
Thanks in advance, sheinke.

**Comment by tstenner** [comment]
The preferred approach is to save and set the global locale before calling `lexical_cast` and reset it afterwards. There's only one problem:

> Because setlocale modifies global state which affects execution of locale-dependent functions, it is undefined behavior to call it from one thread, while another thread is executing any of the following functions: std::fprintf, std::isprint, std::iswdigit, std::localeconv, std::tolower, std::fscanf, std::ispunct, std::iswgraph, std::mblen, std::toupper, std::isalnum, std::isspace, std::iswlower, std::mbstowcs, std::towlower, std::isalpha, std::isupper, std::iswprint, std::mbtowc, std::towupper, std::isblank, std::iswalnum, std::iswpunct, std::setlocale, std::wcscoll, std::iscntrl, std::iswalpha, std::iswspace, std::strcoll, std::wcstod, std::isdigit, std::iswblank, std::iswupper, std::strerror, std::wcstombs, std::isgraph, std::iswcntrl, std::iswxdigit, std::strtod, std::wcsxfrm, std::islower, std::iswctype, std::isxdigit.

Liblsl calls lexical_cast from non-main threads so this could cause almost impossible to debug crashes in applications using liblsl, so this somehow rules out lexical_cast for float conversions (and no, neither `BOOST_LEXICAL_CAST_ASSUME_C_LOCALE` nor `BOOST_NO_STD_LOCALE` help).

**Comment by mgrivich** [comment]
Perhaps it is just best to remove lexical_cast from LSL. There should be a thread-safe alternative out there.

**Comment by tstenner** [comment]
There is (std::ostringstream with an imbued locale), it's just somewhat slower. For C++17 there's [charconv](https://en.cppreference.com/w/cpp/header/charconv) with more or less drop in replacements for C++11

**Comment by agricolab** [comment]
I just wanted to inform that i found a likely related issue with locale, spyder and pylsl on linux mint 19 cinnamon. Specifically, when i created a stream-outlet, the version returned from streaminfo.as_xml() was using a comma when run in spyders ipython, but a point when run from python or ipython started in bash. A consequence of this is that streams created within spyder could not be properly resolved, even not in spyder itself. 

This apparently was linked to X11s locale settings regarding region, as i was using german defaults for region, i.e. e.g. measurements and calendar (but not system-language, where i prefer english). Setting X11 to use english everywhere fixed that, and version is now using a point in spyder too, and the outlets are properly resolved.

**Comment by tstenner** [comment]
With #25 merged or without it?

**Comment by agricolab** [comment]
good question, will have to check when at that PC again.

**Comment by agricolab** [comment]
Ok. I was running pylsl 1.12.2.
I could recreate the error where the outlet had ```<version>1,1000000000000001</version>```, and where the receiver did not properly resolve:
- when regional was set to german in X11
- and when the outlet was created in spyder. 
When created from the terminal, it always worked. Interestingly, calling locale from the shell or via os.system showed the same output for both cases, and regardless of which language was set for regional:
```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```
More importantly, upgrading pylsl to 1.13 with ```conda install -c tstenner pylsl``` fixed the issue, and spyder shows now a dot with the same settings it showed a comma earlier.
