### ISSUE TITLE
CMake export - "LSLConfig.cmake" or "liblslConfig.cmake"?

### ISSUE THREAD

**Issue by cboulay** [sccn/liblsl#47]
CMake's [find_package in config mode](https://cmake.org/cmake/help/latest/command/find_package.html#full-signature-and-config-mode) looks for a file named `<PackageName>Config.cmake`.

In the template application, cmake/Findliblsl.cmake [calls `find_package(LSL...`](https://github.com/labstreaminglayer/AppTemplate_cpp_qt/blob/master/cmake/Findliblsl.cmake#L27).

So it's looking for LSLConfig.cmake

In liblsl, the name of the exported file is set here:
https://github.com/sccn/liblsl/blob/master/CMakeLists.txt#L230-L233

which becomes liblslConfig.cmake

Note that the template application parent `find_package` is to `find_package(liblsl)`.

For consistency, I think we should make the template application call `find_package(LSL)`, rename the find-module to `FindLSL.cmake`, and also modify the export name to LSLConfig.cmake.

Thoughts?

**Comment by tstenner** [comment]
For that the `LSLCMake.cmake` needs to be included by the exported `FindLSL.cmake`, which currently doesn't happen. So, there are three steps:

1. add `LSLCMake.cmake`s functionality to the exported configuration (behind a configuration macro, so it can be included safely)
2. rename the export configuration name
3. give `FindLSL.cmake` a better name, as it currently has some repository specific logic

**Comment by tstenner** [comment]
Let me shorten that:

1. Merge #53 
2. Replace the references to `Findliblsl.cmake` with the snippet in #53
3. Done.
