### ISSUE TITLE
7zip is annoying

### ISSUE THREAD

**Issue by cboulay** [sccn/liblsl#49]
I was helping someone via remote control. I went to get the latest liblsl and was faced with a 7zip file that I couldn't open on their computer. Asking them to install 7zip because we're too cool for zip is annoying.

**Comment by tstenner** [comment]
For the liblsl package I can sort of agree, but for the Apps with Qt the size difference is too much.

**Comment by tstenner** [comment]
Changed in 32d4c6c5c7922dfd4facb48a3b95c5a08e200d91
