### ISSUE TITLE
Build  the lib under x64

### ISSUE THREAD

**Issue by hoangphamemotiv** [sccn/liblsl#52]
hi, i see that seem we just have cmake config for building x86. do we have plan to update it to x64?
or did i miss something?

**Comment by cboulay** [comment]
It builds under x64. Tell me what platform / arch / compiler are you using and I can point you to specific instructions.

**Comment by hoangphamemotiv** [comment]
@cboulay i am using Windows, x64, VS2017. ^^!

**Comment by tstenner** [comment]
It depends on which [CMake Generator](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html) you're using.

For the Visual Studio generators, you have to specify the toolset ([e.g. `cmake -G "Visual Studio 16 2019" -A x64`](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2016%202019.html#platform-selection), for Makefile / Ninja generators you have to have the correct compiler set in your environment variables, e.g. by launching the "Native command prompt for x64".

**Comment by hoangphamemotiv** [comment]
thank @tstenner i missed it on the configure step. 
now it works for me
