### ISSUE TITLE
Linkage errors when attempting to install liblsl through VS17 CMake.

### ISSUE THREAD

**Issue by NathanSteadman** [sccn/liblsl#55]
When attempting a build and install of liblsl through Visual Studio Community 2017 15.9.19 the errors detailed in the attached image are thrown when attempting to install through the integrated CMake menu.

![VS_Error](https://user-images.githubusercontent.com/6660548/73801527-94895380-47b2-11ea-911c-a572f475ae68.png)

**Comment by cboulay** [comment]
I fixed it with something that's maybe a bit of a hack. It's probably better to handle linking Bcrypt in cmake... but this will do for now.

**Comment by cboulay** [comment]
Other options:

* In cmake, only for windows with msvc <= 2017, add `bcrypt` to the list of `target_link_libraries`
* In cmake, only for windows with msvc <= 2017, set the compiler flag `BOOST_UUID_FORCE_AUTO_LINK`.
* Leave it as is

**Comment by SoulSharer** [comment]
fixing CMakeLists.txt (line 147 of 1.13.1 release) to ```
target_link_libraries(lslboost PUBLIC bcrypt PRIVATE
		$<$<BOOL:${MINGW}>:wsock32 ws2_32 winmm>
```
solved the issues for me.
