### ISSUE TITLE
Windows, some configs produce liblsl64.dll, but most produce lsl.dll

### ISSUE THREAD

**Issue by cboulay** [sccn/liblsl#56]
Fresh clone.

| Visual Studio Version                                           | CMake                   | Result |
| ---------------------------------------------------- | -------------------- | ------ |
| Visual Studio 2017 Version 15.9.18                       | integrated cmake | liblsl64.dll |
| x64 Native Tools Command Prompt for VS 2017 | cmake .. -G "Visual Studio 15 2017 Win64"| lsl.dll |
| Visual Studio 2019 Version 16.4.4                         | integrated cmake | lsl.dll |
| x64 Native Tools Command Prompt for VS 2019 | cmake .. -G "Visual Studio 16 2019" -A x64| lsl.dll |

**Comment by cboulay** [comment]
Changing the cmake option `LSL_NO_FANCY_LIBNAME` to `OFF` produced liblsl64.dll on VS 2019.

So, I'm fine with switching over to lsl.dll by default. Most Windows libraries I use don't put the architecture bitness in the filename, though some do. Same thing with the lib prefix.

I think that `LSL_NO_FANCY_LIBNAME` is a bad name for an option, especially because in the cmake code it's checked with `if(NOT LSL_NO_FANCY_LIBNAME)` double-negative, making it a bit unintuitive. And what's the default behaviour on Mac / Linux? Those platforms should prefix with `lib` (i.e., `liblsl.so`) by default, right? Turning this argument ON doesn't change that, right?

What if we instead have an option `LSL_FORCE_FANCY_LIBNAME` and set it to off by default? Then the default behaviour will be platform-specific, with windows yielding lsl.dll and Linux yielding liblsl.so.

This still doesn't solve the problem why VS2017 cmake integration gave liblsl64.dll

**Comment by tstenner** [comment]
If there's a residual config with `LSL_NO_FANCY_LIBNAME=ON` set it will produce `liblsl64.dll`.

> What if we instead have an option LSL_FORCE_FANCY_LIBNAME and set it to off by default?

Good idea, I've changed it.

> And what's the default behaviour on Mac / Linux? Those platforms should prefix with lib (i.e., liblsl.so) by default, right? Turning this argument ON doesn't change that, right?

Right, the default prefix is `lib`; with the old behaviour the libname is changed to `liblsl` and the prefix is removed.

> This still doesn't solve the problem why VS2017 cmake integration gave liblsl64.dll

I think there's a configuration file with the values set somewhere. The default build folder for VS2017 is outside the source folder, so it could survive a fresh clone.

**Comment by tstenner** [comment]
Can this issue be closed?

**Comment by cboulay** [comment]
I haven't been using VS2017 so I can't be sure it's gone, but I'll assume it was a problem on my end.
