### ISSUE TITLE
Windows, cmake `--target package` puts package in {root}/package

### ISSUE THREAD

**Issue by cboulay** [sccn/liblsl#63]
I realize that there have been a bunch of changes to the cmake files to help with CI builds. It's an iterative process and I'm just making a note of what's currently broken.

`D:\Tools\Neurophys\labstreaminglayer\LSL\liblsl\build_win>cmake --build . --config Release -j --target package`

> CPack: - package: /package/liblsl-1.14.0-Win64.zip generated.
  CPack: - package: /package/lsltests-1.14.0-Win64.zip generated.

This ends up in my D:\package folder.

I guess we should have a more sane package directory.

**Comment by tstenner** [comment]
I can't reproduce this on my machine:

```
> rd /Q /s build & cmake -S . -B build & cmake --build build --config Release -j --target package
…
-- Git version information: master/v1.14.0b1-1-g34719d68
…
  CPack: Create package
  CPack: - package: C:/Users/stenner-t/source/labstreaminglayer/LSL/liblsl/build/lsl-1.14.0-win64.zip generated.
```

**Comment by cboulay** [comment]
My own issue is stale. I'll reopen if I encounter it again. I use a different worfklow these days so I may not.
