### ISSUE TITLE
Possible to use localhost/127.0.0.1 as KnownPeers in lsl_api.cfg?

### ISSUE THREAD

**Issue by balpeaux** [sccn/liblsl#86]
Hello,

I'm trying to use the settings on lsl_api.cfg, however, I'm not sure that they are actually read.
Is there a way to check if the settings are being loaded?

Finally, I want to be able to run lsl without any real network interfaces up.
Is it possible to use only the local host 127.0.0.1 to send and receive packages?

Thank you in advance

**Comment by tstenner** [comment]
> Is there a way to check if the settings are being loaded?

I mostly add an invalid setting in the lsl_api.cfg and check for the error message.

> Finally, I want to be able to run lsl without any real network interfaces up.
Is it possible to use only the local host 127.0.0.1 to send and receive packages?

Yes, but with a big disclaimer. `KnownPeers` sends unicast requests to all configured ports, so this isn't ideal. You can, however, add a multicast route to the loopback interface to make it work (see also #92).
