### ISSUE TITLE
Error using chol Matrix must be positive definite on liblsl 1.14 + LabRecorderCLI

### ISSUE THREAD

**Issue by garygan89** [sccn/liblsl#87]
## Environment Info
```
debian@sr-imx8:~/liblsl-build/liblsl/build/install/bin$ ./lslver
LSL version: 114
git:v1.14.0b4-2-g1eaaf08c/branch:master/build:/compiler:GNU-10.2.0/link:shared

Tried both LabRecorderCLI tagged v1.13.1 and the latest from [master] branch.
```

## Issue
When using LSL v1.14 with LabRecorder (master branch from https://github.com/labstreaminglayer/App-LabRecorder), the following error occurred in 1 out of 5 XDF recordings. It is really hard to reproduce, and Google search points me to https://github.com/labstreaminglayer/App-LabRecorder/issues/15, which mentioned a clock offset bug introduced in liblsl1.13. Is it still unsolved and somehow creep to 1.14? 

I'm running the consumer using the sample code, SendDataC. I also make sure to press 'Enter' to correctly closed the file, as follows:

```
debian@sr-imx8:~$ LabRecorderCLI SendDataC4.xdf 'type="EEG"'
Found SendDataC@sr-imx8 matching 'type="EEG"'
Starting the recording, press Enter to quit
2020-10-16 00:09:39.348 (   1.003s) [        AE0941C0]             common.cpp:50    INFO| git:v1.14.0b4-2-g1eaaf08c/branch:master/build:/compiler:GNU-10.2.0/link:shared
Opened the stream SendDataC.
Received header for stream SendDataC.
Started data collection for stream SendDataC.

Offsets thread is finished
Wrote footer for stream SendDataC.
Closing the file.
```

Not sure if I should downgrade my liblsl to 1.12 or even earlier.

**Comment by cboulay** [comment]
Closing in favour of https://github.com/labstreaminglayer/App-LabRecorder/issues/44
